### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#128]
Please complete the following:
1) Move the "Volleyball Unite 2021(TM) . All Rights Reserved" to the very bottom of the footer.  Please add a TM (trademark) symbol rather than the C for Copyright.  We have trademarked Volleyball Unite.  Remove 2020. 

2.  Add a landing screen to the homepage with a Canada and USA flag concept.  If they click on USA flag it goes to .com. If they click on Canada flag it goes to .ca website.  Or better yet can we have the .com automatically appear for USA IP addresses?  and the .ca automatically appear when we a Canadian IP address searches Volleyball Unite?

- If we use a flag concept it might be cool to have 2 animated 3-D athletes holding each of the flags and have the flags moving.  

3. Once these changes are completed please move the site to the volleyballunite.com  URL

**Comment by vayuzpriya** [comment]
Move the "Volleyball Unite 2021(TM) . All Rights Reserved" to the very bottom of the footer. Please add a TM (trademark) symbol rather than the C for Copyright. We have trademarked Volleyball Unite. Remove 2020. : fixed

Add a landing screen to the homepage with a Canada and USA flag concept. If they click on USA flag it goes to .com. If they click on Canada flag it goes to .ca website. Or better yet can we have the .com automatically appear for USA IP addresses? and the .ca automatically appear when we a Canadian IP address searches Volleyball Unite?  flag added on header 
@technicalbirdVayuz  Pls have a look

**Comment by stevekamps** [comment]
Move the "Volleyball Unite 2021(TM) . All Rights Reserved" to the very bottom of the footer.

Please center the Canada and USA flags below the Join Now button on the cell phone version

**Comment by stevekamps** [comment]
I like the concept of the flags.  No need for a landing page with flags. Just center them on the cell screen version below the Join Now Button

**Comment by technicalbirdVayuz** [comment]
please check
