### ISSUE TITLE
College Verify Process not working to coach email

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#611]
I have created College XYZ and College ABC to try out the verify process. 

The password needs to come through to the coach email address not to the fake mailinator address.  This looks super unprofessional and needs to be fixed

**Comment by stevekamps** [comment]
Here is what we need:
1)  We manually hit "Verify Collge" in the dashboard
2) Copy and paste the URL into an individual email
3) Send a templated email to the coach (manually outside of VU) with a welcome and the URL to claim page
4) Coach enters their email that has already been registered with the College through the CSV upload
5) Coach receives a temporary password automatically to his/her college email as in step #4 above
6) Coach then signs in with college email and temporary email
7) coach changes the temporary password to their own 

We have decided not to go with a complex mass email to everyone to claim a page.   We realize that is an enhancement and we would rather touch base with each coach one on one with the above process. 

Please make this #1 priority as we want to launch

**Comment by technicalbirdVayuz** [comment]
Sharing the modified, Flow

1)  We manually hit "Verify Collge" in the dashboard - **No Change Required**
2) Copy and paste the URL into an individual email - - **No Change Required**
3) Send a templated email to the coach (manually outside of VU) with a welcome and the URL to claim page - - **No Change Required**
4) Coach enters their email that has already been registered with the College through the CSV upload - - **No Change Required**
5) Coach receives a temporary password automatically to his/her college email as in step #4 above 
Change Required: Instead of Sending mail to Association Email, Mail should be sent to head coach email - Done

6) Coach then signs in with college email and temporary email 
No Changes Required but if the coach email does contains mailinator then it has to use that email only to sign in. Please don't use mailinator.com if that is a problem

7) coach changes the temporary password to their own  - No changes required



@stevekamps Please check. Build will be live in 15 min

**Comment by technicalbirdVayuz** [comment]
Updated in Production also

**Comment by stevekamps** [comment]
I don’t understand what you are saying in point #6.

I don’t want mailinator involved at all for any of the College teams 

Password should go to college coach email. Then they sign in with college coach email and temporary password

**Comment by technicalbirdVayuz** [comment]
Don't use mailinator id while uploading the data from csv. 

Also, As per the original flow, there are 2 emails, 1 is college email & other 1 is coach email, email will be received on coach email & he has to login with college email.

Let me know if there is any confusion

**Comment by stevekamps** [comment]
The coach email and college email are the same thing. 

I.e. ***@***.***

We have added the coach email to the CSV. This is the only email we know.

They need to be able to claim their page with this email

**Comment by technicalbirdVayuz** [comment]
Please check the flow now.

**Comment by stevekamps** [comment]
Not working.  When I enter the coach email it says "User Verified". then goes to the sign in page.  It should have a message that pops up that says "User - Verified.  A temporary password has been sent to your email. 
And a temporary email is not being sent so there is no way for them to login.

**Comment by technicalbirdVayuz** [comment]
We have used your Id, hope you have received the email.

Also, if you want to check with the mailinator ids then also it can be checked now. 

 The new build has been deployed on production
![image](https://user-images.githubusercontent.com/18699624/162487262-7079f630-da93-4d65-b9b8-eee68f21b085.png)

**Comment by stevekamps** [comment]
I don’t understand the link to signin?

**Comment by technicalbirdVayuz** [comment]
That was tested on local. I checked on local before making the build live on production. It will be https://volleyballunite.com/ when checked from the production.

**Comment by stevekamps** [comment]
The process works.  A couple of additional tasks:
1)  We need to have a message that pops up after they verify their email.   "User - Verified. A temporary password has been sent to your email"
2) Once they log back in let me straight into the platform without having the need for us to verify again. I have added the screen below of what I am talking about.
![approved](https://user-images.githubusercontent.com/77851393/162502704-b4d51bf0-3b84-4c3a-b7bc-469caf2aa191.jpg)

**Comment by technicalbirdVayuz** [comment]
Created new issue. As the original issue has been covered last week
