### ISSUE TITLE
Appstore & Google PlayStore Update

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#651]
We have created a new description for appstore and google playstore. Emailed to Kushagra

We have created 9 new images for appstore (5.5", 6.5", and 12.2").  Sent to Kushagra.

Please push new app ASAP with the order of the files. Please note there is no #9 image.

Please push today as we want to launch Monday

**Comment by ShikharVayuz** [comment]
HOW IT WORKS
ATHLETES
1. Sign Up
A powerful feature rich App that keeps all your recruiting information in one place. Volleyball Unite allows Athletes to create a FREE profile to showcase their academic and volleyball achievements. Athletes can also add Physical Attributes, Uniform #, pictures, and videos to their Profile and Feed. 

2. Search for College Volleyball Programs 
Volleyball Unite’s advanced search feature allows Athletes to search for all College volleyball programs across the USA that fit their specific recruiting needs and requirements. Search by League, Division, Region, Conference, State, City, School Type, Enrollment #’s and Tuition $$$.

3. Add Colleges to your Wishlist
The VU Wishlist allows Athletes to add Colleges to their personal “Wishlist” that fit academic and volleyball aspirations. Colleges will receive instant notification once they are added to an Athlete’s Wishlist.

4. UNITE with teammates and Coaches
The Volleyball Unite network enables Athletes to UNITE with other users and share valuable information.

5. Search and Add Events to Your Profile
Athletes can Search the network using Volleyball Unite’s powerful search feature and then add events they are attending to their VU profile. Recruiters can now easily see an athletes future Event schedule in seconds.

6. Follow Organizations 
Athletes can stay up to date by Following their favorite Colleges, Clubs, Regional Associations, and High Schools.
 
7. Get Scouted – Get Recruited - Commit
Once committed to a College….Athletes can update their profile and be added to the upcoming roster for the College they have committed to.


COLLEGE PROGRAMS

1.	Showcase your College Program
College programs can add Videos, Blogs, Events, Past/Current/Future Rosters, Press Releases, Events, Web Site Links and Contact Info.  

2.	Find Athletes
Search the App or web from courtside to discover Athletes that fit your team’s needs. Search by Position, Uniform Number, Club Team, State, City, and Available status.

3.	Create Events
Create and Showcase public events for the entire VU Network to see.  Users can search for events to attend such as tryouts, tournaments, fundraisers, camps, and clinics.

4.	Save Budget
Volleyball Unite saves every College program time and money with all the advanced Recruiting and Marketing features that have been created. Search for Athletes, post press releases, create Events at a click of a button from the comfort of your office or home.

COLLEGE COACHES

1. Sign Up
A powerful feature rich App that keeps all your recruiting information in one place. Volleyball Unite allows Coaches to create a FREE profile to showcase all their Coaching achievements. The Volleyball Unite Network also enables College Coaches to review Athlete profiles, athletic information, endorsements, academic information, physical attributes, pictures/videos and build your very own “Virtual Bench” for all future recruiting efforts.

2. Follow & Unite
Follow Colleges, Clubs and Organizations of interest. Unite with Athletes, Coaches, Clubs and Referees. Build your network.

3. Find Athletes
Search Volleyball Unite on the web or App from courtside to discover Athletes that fit your programs specific requirements. Search by Physical Attributes, Academic Interests, Gender, Grad Year, Position, Uniform Number, Club Team, State, City, and Available status.

4. Communicate
Streamline your recruiting efforts with direct email communication to Athletes.

5. Group Chat
Keep all of your communication organized and in one location with Volleyball Unite’s Group chat feature. Athletes you invite to your Group will receive instant push notifications to their cell phones. Push out Event notifications instantly as well. 

6.  Virtual Bench 
Add prospective Athletes to your Virtual Bench so that you can continue to follow their progress and streamline your future recruiting efforts and budget.


HIGH SCHOOL & CLUB COACHES

1. Sign Up
A powerful feature rich App that keeps all your recruiting information in one place. Volleyball Unite allows Coaches to create a FREE profile to showcase all their Coaching achievements. The Volleyball Unite Network also enables School and Club Coaches to review Athlete profiles, athletic information, endorsements, academic information, physical attributes, pictures/videos and build your very own “Virtual Bench” for all future recruiting efforts.

2. Unite
UNITE with Coaches, grow your network, and build your recruiting pipelines across the nation.
3. Group Chat
Keep all of your communication organized and in one location with Volleyball Unite’s Group chat feature. Athletes you invite to your Group will receive instant push notifications to their cell phones. Push out Event notifications instantly as well.
4. Follow Organizations
Follow your favorite Organizations and keep up to date with press releases, signings, and valuable volleyball information.  
ORGANIZATIONS
1. Sign up
Create your FREE Organization Page in minutes. Organizations include Colleges, Clubs, High Schools, and Regional/State Associations.
2. Showcase your Organization
Optimize your Organization page with contact details and press releases.  Post to your public Feed and Showcase your Athletes, Coaches, and Teams. Build your brand.
3. Add Rosters
Build your teams and add all Athletes to their respective roster to increase recruiting exposure for all your Athletes and Coaches.
4. Create Events
Create public events for the entire Volleyball Unite Network.  Users can search for Events to attend such as tryouts, tournaments, fundraisers, camps, and clinics.
5.Grow Membership
With Volleyball Unite’s powerful FREE Feed, Organizations can Unite with others to grow membership numbers and retain existing membership through engaging posts and announcing future Events.
REFEREES
1. Sign Up
Create your FREE Referee Profile and Unite with other Referees, Coaches, and Athletes on Volleyball Unite. 
2.  Follow Organizations
Stay up to date in the volleyball world by Following your favorite Colleges, Clubs, Regional Associations, and High Schools.
3. Group Chat 
Create Referee groups for instant communication.

**Comment by ShikharVayuz** [comment]
![image](https://user-images.githubusercontent.com/86296418/191973596-eda160c2-00e2-408b-9fc2-05c74f3adbd4.png)
@stevekamps  The description shared is reaching its max limit on play store. Please look into this and shorten up the content.

**Comment by stevekamps** [comment]
Is the 4000 character limit for the appstore or Play store?

**Comment by stevekamps** [comment]
Please also change the category to "Sports" rather than "Social Network"

**Comment by ShikharVayuz** [comment]
> Is the 4000 character limit for the appstore or Play store?
> 

It is for the play store listing

**Comment by stevekamps** [comment]
Volleyball Unite is North America’s Premier Volleyball Recruiting Network specifically designed for Athletes, Coaches, Colleges, Clubs, High Schools & Referees enabling the entire volleyball community to UNITE and share valuable information.


HOW IT WORKS


ATHLETES

1. Sign Up
A powerful feature rich App that keeps all your recruiting information in one place. Athletes can create a FREE profile to showcase their academic and volleyball achievements. Add Physical Attributes, Uniform #, pictures, and videos to the Profile and Feed. 

2. Search for College Volleyball Programs 
VU’s advanced search feature allows Athletes to search for all College volleyball programs across the USA that fit their specific recruiting needs and requirements. Search by League, Division, Region, Conference, State, City, School Type, Enrollment and Tuition.

3. Add Colleges to your Wishlist
The VU Wishlist allows Athletes to add Colleges to their personal “Wishlist” that fit academic and volleyball aspirations. Colleges will receive instant notification once they are added to an Athlete’s Wishlist.

4. UNITE with teammates and Coaches
The VU network enables Athletes to UNITE with other users and share valuable information.

5. Search and Add Events to Your Profile
Athletes can Search the network using VU’s powerful search feature and then add events they are attending to their profile. Recruiters can see which events an athlete is attending.

6. Follow Organizations 
Athletes can stay up to date by Following their favorite Colleges, Clubs, Regional Associations, and High Schools.
 
7. Get Scouted – Get Recruited - Commit
Once committed to a College, Athletes can update their profile and be added to the upcoming roster for the College they have committed to.


COLLEGE PROGRAMS

1.	Showcase your College Program
College programs can add Videos, Blogs, Events, Past/Current/Future Rosters, Press Releases, Events, Web Site Links and Contact Info.  

2.	Find Athletes
Search the App or web from courtside to discover Athletes that fit your team’s needs. Search by Position, Uniform Number, Club Team, State, City, and Available status.

3.	Create Events
Create and Showcase public events for the entire VU Network to see.  Users can search for events to attend such as tryouts, tournaments, fundraisers, camps, and clinics.

4.	Save Budget
VU saves every College program time and money with all the advanced Recruiting and Marketing features that have been created. Search for Athletes, post press releases, and create Events.

COACHES

1. Sign Up
A powerful App that keeps all your recruiting information in one place. Coaches can create a FREE profile to showcase all their Coaching achievements. Coaches can review Athlete profiles, athletic information, endorsements, academic information, physical attributes, pictures/videos and build your very own “Virtual Bench” for all future recruiting efforts.

2. Unite
UNITE with Coaches, grow your network, and build your recruiting pipelines across the nation.

3. Group Chat
Keep all of your communication organized and in one location with VU’s Group chat feature. 

4. Follow Organizations
Follow your favorite Organizations and keep up to date with press releases, signings, and valuable volleyball information.  


ORGANIZATIONS

1. Sign up
Create your FREE Organization Page in minutes. Organizations include Colleges, Clubs, High Schools, and Regional/State Associations.

2. Showcase your Organization
Optimize your Organization page with contact details and press releases.  Post to your public Feed and Showcase your Athletes, Coaches, and Teams. 

3. Add Rosters
Build your teams and add all Athletes to their respective roster to increase recruiting exposure for all your Athletes and Coaches.

4. Create Events
Create public events for the entire VU Network.  Users can search for Events to attend such as tryouts, tournaments, fundraisers, camps, and clinics. 

5.Grow Membership
With VU’s powerful Feed, Organizations can grow and retain membership numbers through engaging posts and Events.

**Comment by stevekamps** [comment]
It is now below 4000 characters

**Comment by stevekamps** [comment]
Looks good. Now just add new images and lets get this in the Appstore
